# Generated by Django 4.2.1 on 2023-05-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_collection_options_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='featured_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
    ]
