# Generated by Django 4.2.1 on 2023-05-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_collection_featured_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
