# Generated by Django 4.2.1 on 2023-05-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cart_cartname_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='orderItemName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
