# Generated by Django 4.2.1 on 2023-05-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_alter_likeditem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeditem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
