# Generated by Django 4.2.1 on 2023-05-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagggeditem',
            name='tagnameitem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
